spring:
 profiles:
  active: dev_uni
 
  
---

spring:
 profiles: dev_uni
 jpa:
  hibernate:
   ddl-auto: create
   naming-strategy : org.hibernate.cfg.ImprovedNamingStrategy
  show-sql: true
 thymeleaf:
  cache: false
  
server:
 port: 8000

db:
 user: afs18
 password: autorkle
 url: jdbc:mysql://mysql.mcscw3.le.ac.uk:3306/afs18
 
---

spring:
 profiles: prod
 jpa:
  hibernate:
   ddl-auto: validate
   naming-strategy : org.hibernate.cfg.ImprovedNamingStrategy
  show-sql: true
 
tomcat:
 remote_ip_header : x-forwarded-for
 protocol_header : x-forwarded-proto
 
  
---

spring:
 profiles: dev_home
 jpa:
  hibernate:
   ddl-auto: validate
   naming-strategy : org.hibernate.cfg.ImprovedNamingStrategy
  show-sql: true
 
server:
 port: 8000

db:
 user: root
 password: ""
 url: jdbc:mysql://localhost:3306/eventApp  
 
 
 